### ISSUE TITLE
update onboarding

### ISSUE THREAD

**Issue by Nfratt** [Kikitheapp/Kikiapp#15]
include Github onboarding

**Comment by alcastonguay** [comment]
Hey @Nfratt, It looks like the added instructions have been placed in the footer of the document. Was this what you intended to do?

**Comment by Nfratt** [comment]
@alcastonguay thanks for noticing. yeah I felt that because it was something to apply in general it should be in the footer. Do you think it should be its own step?

**Comment by alcastonguay** [comment]
@Nfratt I think it would be a good idea to make a section for code standards or best practices. Right now we only have the one but we will probably have more as we go along.
