### ISSUE TITLE
404 when navigating to internal page with URL

### ISSUE THREAD

**Issue by alcastonguay** [Kikitheapp/Kikiapp#47]
404 page not found error is provided when a user attempts to access any page other then the index using the url 

For example: https://kikiapp.org/aboutUs

This issue does not appear when working locally, after running the app using the react start script.

**Comment by alcastonguay** [comment]
Did some research and quickly found the problem.

https://itnext.io/so-you-want-to-host-your-single-age-react-app-on-github-pages-a826ab01e48

Will attempt to implement next.

**Comment by Nfratt** [comment]
Checked this out with Amanda. She's looking into using HashHistory under the "Handling Hard Refreshes on Routes that are not your Root Route" section. I'm looking into the more hacky force refresh to main under the For your info at the end of the article.
